### PR TITLE
Support Symfony 6

### PR DESCRIPTION
**Pull request by norkunas**
# Pull Request

## What does this PR do?
Adds support for Symfony 6 and fixes tests

## PR checklist
Please check if your PR fulfills the following requirements:
- [ ] Does this PR fix an existing issue?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

### CODE REVIEW

**Comment by norkunas** [comment]
Maybe we could also increase lowest constraint from Symfony 4.0 to 4.4? which is lowest maintained version

**Comment by curquiza** [comment]
> Maybe we could also increase lowest constraint from Symfony 4.0 to 4.4? which is lowest maintained version

Let's fix the CI first.

We'll add lower version support if asked by the community, and in another PR, what do you think?

**Comment by norkunas** [comment]
OK

**Comment by curquiza** [comment]
@norkunas, I realized I did not get well first your question about Symfony 4.0, my bad, I've just opened an issue: https://github.com/meilisearch/meilisearch-symfony/issues/141

**Comment by norkunas** [comment]
Failing to find a way to support both php 7 and 8 worlds :/

**Comment by curquiza** [comment]
Thanks for having tried!!

I close this PR in favor of this issue #143 

Feel free to re-open another PR if you have a solution, or want to try something!

**Comment by norkunas** [comment]
Dont have more time now,will try on monday :)

**Pull request closed without merging**
