### PR TITLE
Test with Symfony 7.1 and leverage its features

### PR DESCRIPTION
**Pull request by norkunas**
# Pull Request

## Related issue
Fixes #<issue_number>

## What does this PR do?
- Adds Symfony 7.1 to CI;
- Uses `ramsey/composer-install` gh action to install dependencies;
- Uses new `DateTimeNormalizer::CAST_KEY` when available to serialize datetimes as timestamps;

## PR checklist
Please check if your PR fulfills the following requirements:
- [ ] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

### CODE REVIEW

**Comment by norkunas** [comment]
Side effect from https://github.com/meilisearch/meilisearch-symfony/pull/322 was that removing `.*` from sf-version, it uses directly the defined version instead of highest, so for 5.4 it uses 5.4.0 instead of 5.4.40

**Comment by norkunas** [comment]
bors merge

**Review by curquiza — APPROVED** [review]
bors merge

**Comment by curquiza** [comment]
bors merge-

**Comment by curquiza** [comment]
bors merge

**Pull request merged**
