### PR TITLE
Use modern structure

### PR DESCRIPTION
**Pull request by norkunas**
# Pull Request

## Related issue
Fixes #<issue_number>

## What does this PR do?
- Moves `Resources/config` dir to `/config`.

See https://symfony.com/doc/current/bundles.html#bundle-directory-structure

Also updated tests namespace as the IDE warned: `Namespace name doesn't match the PSR-0/PSR-4 project structure` and it's also recommended in the given link.

## PR checklist
Please check if your PR fulfills the following requirements:
- [ ] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

### CODE REVIEW

**Comment by brunoocasali** [comment]
Hi @norkunas thanks a lot for your time!

Two questions:

Does this represent a breaking change for the users (or should they do anything on their side to use it)? I believe not, but just confirming.

And, how can we automate this type of "alert"?

**Comment by norkunas** [comment]
> Hi @norkunas thanks a lot for your time!
> 
> Two questions:
> 
> Does this represent a breaking change for the users (or should they do anything on their side to use it)? I believe not, but just confirming.
> 
> And, how can we automate this type of "alert"?

No breaking changes unless people includes bundle config somewhere else, but they shouldn't :)

Not sure what you are asking about automation 🤔

**Comment by brunoocasali** [comment]
> Not sure what you are asking about automation 🤔

I mean, in as an Action in CI...

**Comment by norkunas** [comment]
It would just waste CI resources I think, as it is one time change

**Review by brunoocasali — APPROVED** [review]
@norkunas thanks for your time, you rocks! 🤘 

bors merge

**Pull request merged**
