### PR TITLE
chore: add testruns for PHP 8.3

### PR DESCRIPTION
**Pull request by Chris53897**
## What does this PR do?
- Add testrun for PHP 8.3 with symfony 6.3
- bump github actions/checkout v3 => v4

### CODE REVIEW

**Review by curquiza — CHANGES_REQUESTED** [review]
Thank you @Chris53897  for this PR!

Can you update the [bors.toml file](https://github.com/meilisearch/meilisearch-symfony/blob/main/bors.toml)?

**Comment by Chris53897** [comment]
@curquiza Of course

**Review by curquiza — APPROVED** [review]
LGTM

bors merge

**Comment by curquiza** [comment]
bors merge-

**Comment by curquiza** [comment]
bors merge

**Comment by curquiza** [comment]
Merging by hand, looks like we have an issue with bors. The tests pass, so everything is good

Capture d’écran 2023-09-20 à 13 28 21

**Pull request merged**
