### PR TITLE
Add PHP8 support

### LINKED ISSUE #51: PHP8 support
Is PHP8 support planned?

### PR DESCRIPTION
**Pull request by norkunas**
Closes #51

### CODE REVIEW

**Review by curquiza — CHANGES_REQUESTED** [review]
Hello @norkunas!

Thanks for this PR!
I forgot to mention you need to update the `bors.toml` (https://github.com/meilisearch/meilisearch-symfony/blob/master/bors.toml) with the following line in the `status` field:
```txt
'integration-tests (PHP 8.0)',
```
Could you update it please?
Thank you very much for this PR!

**Comment by norkunas** [comment]
Sure, updated :)

**Comment by curquiza** [comment]
bors try

**Review by curquiza — APPROVED** [review]
awesome!

bors merge

**Comment by norkunas** [comment]
Thanks for the merge :)

**Pull request merged**
