### PR TITLE
Add option to meili:import command to override default timeout

### LINKED ISSUE #131: Ability to set request timeout
Sometimes when you import a lot of data, 5 sec as defined [here](https://github.com/meilisearch/meilisearch-php/blob/0b592c1d2b3e642d618254a7ff5716874b72fabf/src/Endpoints/Indexes.php#L186) is not enough and the command `meili:import` fails with the error: 
```
[MeiliSearch\Exceptions\TimeOutException (408)]  
  Request timed out 
```

The idea is to add an option to configure a timeout when importing.

### PR DESCRIPTION
**Pull request by revenkroz**
# Pull Request

## What does this PR do?
Fixes #131

## PR checklist
- [x] Does this PR fix an existing issue?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

### CODE REVIEW

**Review by curquiza — APPROVED** [review]
Thanks @revenkroz for this PR :)

Sorry for the delay

bors merge

**Comment by curquiza** [comment]
Only the `Code style` faliure comes from your PR, not the one regarding PHP 8.0. We have to fix this in another PR

**Comment by curquiza** [comment]
bors try

**Review by curquiza — APPROVED** [review]
Before I merge, @revenkroz, can you give an example of how using your addition, so that I can document it? :)

**Comment by revenkroz** [comment]
@curquiza 
`bin/console meili:import --response-timeout=<timeout in ms>`

For example:
`bin/console meili:import --response-timeout=10000` for 10 seconds as timeout

**Comment by curquiza** [comment]
Thank you so much @revenkroz!

bors merge

**Pull request merged**
