### PR TITLE
Add phpmd to project

### LINKED ISSUE #164: Add PHPMD to improve code quality
**Description**
A good practice is to add [PHPMD](https://phpmd.org/) to the project so we can check the code against good practices.

**Basic example**
The code can be validated by running:
```bash
$ composer phpmd
```

**Other**
We could split the PHPMD into 2 phases, the first one to add PHPMD to the project and the second to fix the current problems.

### PR DESCRIPTION
**Pull request by jonatanrdsantos**
# Pull Request

## What does this PR do?
Fixes #164

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

### CODE REVIEW

**Comment by jonatanrdsantos** [comment]
Seems that PHPMD tools have a problem and don't work across all versions, better deep understanding is needed on this.

**Comment by brunoocasali** [comment]
I moved this PR to draft @jonatanrdsantos so you can work without pressure 🕺

**Comment by brunoocasali** [comment]
@jonatanrdsantos do you want to keep working in this PR?

**Comment by jonatanrdsantos** [comment]
Hi @brunoocasali , no you can close this or pass to another one.

**Comment by brunoocasali** [comment]
Closing due inactivity :)

Feel free to re-open @jonatanrdsantos 💪

**Review by brunoocasali — APPROVED** [review]
Since we removed the dependency on illuminate libraries, I just rebased your branch, and now your configuration works!

Thanks!

**Comment by brunoocasali** [comment]
bors merge

**Pull request merged**
