### PR TITLE
Add pre-release tests in github action

### PR DESCRIPTION
**Pull request by alallema**

### CODE REVIEW

**Review by curquiza — CHANGES_REQUESTED** [review]
Can you remove the curl check in both yml file? :)

**Review by curquiza — APPROVED** [review]
thanks!!! :)

bors merge

**Comment by alallema** [comment]
Also the code fails due to memory allocation in the config that I fixed it on the PR of the release #101 do I put it here too?

**Comment by alallema** [comment]
Opps too late you are fast

**Comment by curquiza** [comment]
Because #101 was merged into `bump-meilisearch-v0.21.0` and not into `main`, pretty sure bors will not merge it.

**Review by curquiza — APPROVED** [review]
bors merge

**Pull request merged**
