### PR TITLE
Fix CS

### PR DESCRIPTION
**Pull request by norkunas**
# Pull Request

## Related issue
Fixes #<issue_number>

## What does this PR do?
- ...

## PR checklist
Please check if your PR fulfills the following requirements:
- [ ] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

### CODE REVIEW

**Review by curquiza — APPROVED** [review]
bors merge

**Comment by curquiza** [comment]
bors merge

**Comment by norkunas** [comment]
bors merge

**Comment by curquiza** [comment]
Not sure it's the fault of bors (for once!)
it's because it expects the following tests to run but cannot find them
- integration-tests (PHP 8.3) (Symfony 6.3.*)
- integration-tests (PHP 8.3) (Symfony 6.4.*)

See [bors config](https://github.com/meilisearch/meilisearch-symfony/blob/main/bors.toml) -> Looks like gitHub does not run all the required tests: https://github.com/meilisearch/meilisearch-symfony/actions/runs/7902542352/job/21568437543

**Comment by connorhu** [comment]
Five is an IT-mythical number. Somewhere there is a cap lurking.

**Comment by norkunas** [comment]
> Not sure it's the fault of bors (for once!) it's because it expects the following tests to run but cannot find them
> 
> * integration-tests (PHP 8.3) (Symfony 6.3.*)
> * integration-tests (PHP 8.3) (Symfony 6.4.*)

yeah, they don't appear even after commit amend :/

**Comment by connorhu** [comment]
Removing unsupported symfony (6.0, 6.1, 6.2, 6.3) versions would be a workround.
versions

**Comment by norkunas** [comment]
but then we'd block people for nothing.. but if there are no other solutions, well then yes..

**Comment by norkunas** [comment]
still some jobs are not started :/

**Comment by norkunas** [comment]
@curquiza managed to fix it.
now these jobs:
```
integration-tests (PHP 8.0) (Symfony 6.0.*) Expected — Waiting for status to be reported
Required
integration-tests (PHP 8.1) (Symfony 6.1.*) Expected — Waiting for status to be reported
Required
integration-tests (PHP 8.2) (Symfony 6.2.*) Expected — Waiting for status to be reported
Required
```
should be removed from repo

**Comment by curquiza** [comment]
@norkunas done ✅ 

bors merge

**Review by curquiza — APPROVED** [review]

**Comment by curquiza** [comment]
And now the famous error I get with Bors 🤦‍♀️ 




Merging by hand!

**Pull request merged**
