### PR TITLE
Update php cs fixer 3

### PR DESCRIPTION
**Pull request by codedge**
This PR adds support for the new [PHP CS Fixer 3](https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/tag/v3.0.0) version.

### CODE REVIEW

**Comment by codedge** [comment]
@curquiza Do I call `borse m e r g e` or what's the plan? 😅

**Review by curquiza — APPROVED** [review]
Thanks @codedge!

Don't worry you don't have the access to merge with bors, only the MeiliSearch team members can.
However, you can `bors try` to check your PR will pass if we do a `bors merge`.
A `bors try` is only useful if your branch is not up-to-date with `main` otherwise the GH check already show you the validity of your PR 🙂
I wrote a guide about our bors usage: https://github.com/meilisearch/integration-guides/blob/main/guides/bors.md

**Comment by curquiza** [comment]
bors merge

**Comment by curquiza** [comment]
(seems like bors has trouble at the moment 😂)

**Comment by curquiza** [comment]
bors merge

**Pull request merged**
