### PR TITLE
Ensure scalar object-ID is used for fetching entities

### PR DESCRIPTION
**Pull request by baumanno**
There currently is a bug in how the search-service retrieves the entities from the results returned from the engine.

It falsely assumes that what it gets back from the engine is a list of object-IDs, when it actually is a list of arrays holding the indexed data for the objects matching the query.

This entire array is passed to `findOneBy`, which expands the `IN(?)`-criteria to a list `IN(?,?,?)`, where the parameters are bound to all indexed properties. This leads to the same entity being returned multiple times, rather than different entities being directly adressed through the scalar object-ID.

A test case illustrates this behaviour, where the Post-contents match the object-ID "1". This test case fails on the current 0.3.0, and passes with the fix proposed in this PR.

### CODE REVIEW

**Comment by baumanno** [comment]
It seems this problem is adressed in #56 , #57 and partly in #23.
I see mentions of refactoring the codebase to remove the old Algolia-inspired reference to objectID. Perhaps until that effort happens, this PR can at least ensure meaningful responses.

This fix is the result of scratching my own itch, as I ran into the exact issue of having indexed fields that are plain integers and can thus be confused with object-IDs (for want of a better term...).

If it does not meet the long-term expectations, I'll try not to be offended if it is declined ;-) I'll just have to add my fork as a dependency then.

**Review by codedge — APPROVED** [review]
LGTM! Until the objectID refactoring is not done, this can surely be a solution to the problem.

**Comment by baumanno** [comment]
I would suggest to tag this as `0.4.0`, since it changes the results returned through the bundle. Clients may be relying on this, and it would be a shame to break their integration. Due to the `0.x.y`, "unstable" versioning right now, they'd have to intentionally bump their dependency to get this update.

I will propose adding a `CHANGELOG.md` in a separate PR.

**Comment by curquiza** [comment]
Hello @codedge and @baumanno!
I put the `breaking` label, which will automatically increase the next version to `0.4.0` :)

FYI, in the future (not the next version, but in the near future) we will add the `primaryKey` field to the search response of MeiliSearch. This will help the developer knowing what is the primary key, so the unique identifier of the dataset. It might help for the objectID refactor.

thanks again!

bors merge

**Pull request merged**
