### PR TITLE
SearchCutoffMs setting

### PR DESCRIPTION
**Pull request by norkunas**
# Pull Request

## Related issue
Fixes #<issue_number>

## What does this PR do?
- Adds support for searchCutoffMs setting

## PR checklist
Please check if your PR fulfills the following requirements:
- [ ] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

### CODE REVIEW

**Review by curquiza — APPROVED** [review]
thank you @norkunas 

bors merge

**Comment by curquiza** [comment]
@norkunas feel free to do a release of course!

**Comment by norkunas** [comment]
@curquiza draft release shows as 0.15.1, but this setting is a new feature, so release should be a minor, not patch.
should I change it to 0.16.0?

**Comment by curquiza** [comment]
Since we are not stable (`0.X.Y`), so far, only the `breaking-change` label on the PR increases the minor automatically.

However, you can change the minor manually if you think it's more relevant. I have no problem with this 😊

**Comment by norkunas** [comment]
Ah, okay

**Comment by curquiza** [comment]
@norkunas not a big deal, but for next time, don't forget to change the version in the Bundle file, as indicated in the CONTRIBUTING.md before releasing 😊 

https://github.com/meilisearch/meilisearch-symfony/blob/main/CONTRIBUTING.md#how-to-publish-the-release

**Comment by norkunas** [comment]
Sorry :expressionless: I think maintaining a version in code is just an overhead, and if one needs it, it should rely on composer to provide installed version :thinking:

**Comment by curquiza** [comment]
Yes, don't worry, not a big deal, no need to recreate a release for this.

**Pull request merged**
