### PR TITLE
Fixing Docker configuration

### PR DESCRIPTION
**Pull request by emulienfou**
Related to issue #6 , add missing Docker configuration

### CODE REVIEW

**Comment by curquiza** [comment]
Still does not work on MacOs. Is this PR still needed? 🙂

**Comment by emulienfou** [comment]
@curquiza this PR add missing code to run Docker locally. However this does not fix the MacOS issue

**Comment by curquiza** [comment]
My bad! I was confused! So, could you rebase your branch please? 🙂

**Comment by emulienfou** [comment]
@curquiza rebased

**Comment by curquiza** [comment]
You need to rebase again since I merged your previous PR #13 sorry 😇 Thanks @emulienfou for your work!

**Pull request merged**
