### PR TITLE
Proximity precision

### PR DESCRIPTION
**Pull request by norkunas**
# Pull Request

## Related issue
Fixes #<issue_number>

## What does this PR do?
- Adds support for proximity precision setting

## PR checklist
Please check if your PR fulfills the following requirements:
- [ ] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

I've based this PR on #317 so will rebase if/after it is merged to get rid of the first commit and also https://github.com/meilisearch/meilisearch-php/pull/606/ should be merged first

### CODE REVIEW

**Comment by curquiza** [comment]
Hello @norkunas 
This PR changes a lot of things. Are they all related to the support of proximityPrecision settings?

**Comment by curquiza** [comment]
I updated my message. The changes were not really visible in the PR description and I missed them

**Comment by norkunas** [comment]
ping @brunoocasali

**Comment by norkunas** [comment]
bors merge

**Pull request merged**
