### PR TITLE
Reduce number of queries

### LINKED ISSUE #134: Too many queries are made in the db
**Description**
For each search result a query [is made](https://github.com/meilisearch/meilisearch-symfony/blob/2bf841639028cb913a9cd69a24ea0464a91da366/src/Services/MeiliSearchService.php#L180) in the database, and if the number of results is huge, so are the queries number.

**Possible fix**
1) Collect all result ids
2) Run one query in the DB
3) Get all entities and sort them as it was in search result

**Screenshots or Logs**

Current state (results is limited to 10).
Screenshot 2021-11-28 at 18 00 12

After possible solution.
Screenshot 2021-11-28 at 17 59 18

### PR DESCRIPTION
**Pull request by revenkroz**
# Pull Request

## What does this PR do?
Fixes #134

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to MeiliSearch!

### CODE REVIEW

**Comment by alallema** [comment]
Hi @revenkroz,
Thank you so much for contributing to Meilisearch ❤️!
@curquiza is on holiday and will review your PR once they are back.

**Comment by curquiza** [comment]
Hello @revenkroz, please ping me when this issue is ready, I mean
- the tests are green
- the PR is not a draft anymore

Thanks for your involvement in this project 🙂

**Comment by brunoocasali** [comment]
Hi, @revenkroz do you have any intentions to keep working on this PR? Let me know if you need anything! 😄

**Comment by brunoocasali** [comment]
Closing since we got no answer! Feel free to reopen the PR if you want to :)

**Pull request closed without merging**
