### PR TITLE
WIP: refactor(core): DataProvider introduced

### LINKED ISSUE #121: (feat): DocumentDataProvider to allow external data sources
**Description**

Hi everyone 👋🏻 

Small suggestion here that can help the bundle supporting extra document data sources, for now, this bundle only support loading document data from entities (without asynchronous supports but more on this later), even if this is the de facto approach when it comes to data handling in Symfony application (thanks to Doctrine), we often use external services like Redis, Kafka and so on, these services contains data and we often need to search on it. 

The idea here is to introduce the idea of `DocumentDataProvider` (or just `_X_DataProvider`) along with a `DataProviderRegistry` which allow to use the data providers and allow each provider to return an array that contains data that we can load into indexes.

**Basic example**

Ok, so, here's a small example: 

```php
final class FooDataProvider implements DataProviderInterface
{
    public function getData(): array
    {
        // Fetch data from external data source and return a valid array
    }

    public static function getIndex(): string // static is not a requirement
    {
        return 'foo';
    }
}
```

Following the same approach, an `EntityDataProvider` can be created to move the logic from the [existing command](https://github.com/meilisearch/meilisearch-symfony/blob/main/src/Command/MeiliSearchImportCommand.php) to a dedicated class.

The final part is a `DataProviderRegistry` which contains and allow to access and interact with the data providers (sort them, filter them and many more) which can be injected in the command to remove some logic on it and ease both the debug and evolution phase.

Regarding the asynchronous support, when using Messenger and regarding https://github.com/meilisearch/meilisearch-symfony/issues/62, adding this layer can help introduce the asynchronous support by allowing to dispatch a message which can call the registry to persist data into MS.

I've already implemented a solution [here](https://github.com/Guikingone/MeiliSearchBundle/tree/master/src/DataProvider) but the final implementation can be improved 🙂 

**Other**

--

Thanks for the feedback and have a great day 🙂

### PR DESCRIPTION
**Pull request by Guikingone**
# Pull Request

Hi 👋🏻 

This PR introduce the `DataProviderRegistry` to help the bundle fetching data from external sources and storing the result into indexes. 

## What does this PR do?

Fixes #121 

## PR checklist

Please check if your PR fulfills the following requirements:
- [X] Does this PR fix an existing issue?
- [X] Have you read the contributing guidelines?
- [ ] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to MeiliSearch!

### CODE REVIEW

**Comment by curquiza** [comment]
Hello @Guikingone! 👋 Nice to see you again!

Thanks for your PR! Can you convert this as a draft since this work is a WIP? :)

Ping me when you want to be reviewed!

**Comment by brunoocasali** [comment]
Hi, @Guikingone do you have any intentions to keep working on this PR? Let me know if you need anything! 😄

**Comment by Guikingone** [comment]
Hi @brunoocasali 👋🏻 

Yes, sorry for the delay, I planned to finish the PR pretty soon, I've been through a pretty busy calendar since 2 months (not to mention open-source work) and I put this PR on the backside of the agenda 😄 

I'll rebase the PR today or tomorrow and continue on the implementation this week-end 🙂

**Comment by brunoocasali** [comment]
Hey @Guikingone I'll close the PR, feel free to reopen in the future, thanks for your work here ❤️

**Pull request closed without merging**
