### PR TITLE
Support Symfony 6

### LINKED ISSUE #143: Support Symfony 6
Make this package work with Symfony 6.

A contributor already tried to make this package work with Symfony 6 but we encountered some issues.
Check out this PR #139

### PR DESCRIPTION
**Pull request by norkunas**
# Pull Request

## What does this PR do?
Fixes #143
Embeds #145 (should be merged first)

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

### CODE REVIEW

**Comment by curquiza** [comment]
bors try

**Comment by curquiza** [comment]
Hello @norkunas! Thanks for this batch of PRs!!

Could you please update the bors.toml file at the root of the repo with the new test: `integration-tests (PHP 8.1)`?

**Comment by norkunas** [comment]
Sure. just please merge the embed PR so I can rebase this one :)

**Comment by curquiza** [comment]
bors try

**Review by curquiza — APPROVED** [review]
thanks !!! bors merge

**Comment by curquiza** [comment]
bors merge

**Pull request merged**
