### PR TITLE
Update version for the next release (v0.7.2)

### PR DESCRIPTION
**Pull request by brunoocasali**
Release notes:

This package version is compatible with [Meilisearch v0.26.0](https://github.com/meilisearch/MeiliSearch/releases/tag/v0.26.0) 🎉 

## 🚀 Enhancements

* Updated `meilisearch-php` to v0.23 (#172) @dependabot
  * ⚠️ Check the [release notes](https://github.com/meilisearch/meilisearch-php/releases/tag/v0.23.0) from `meilisearch-php` for more information.

### CODE REVIEW

**Review by alallema — APPROVED** [review]
LGTM!

**Comment by brunoocasali** [comment]
I thought a lot about this version if it should be 0.8.0 or just 0.7.2. Since in my understanding, we don't expose the Meilisearch client directly to the end-user, the current breaking changes are not breaking to the symphony package.

But just to be sure, we don't expose publicly the client, right @curquiza? (I found only `private`/`protected` `$client` references).

**Comment by brunoocasali** [comment]
@alallema 
> LGTM! (1 minute ago)

Fastest in the west!! 😆

**Comment by curquiza** [comment]
For me it's not breaking. The release version of symfony and the versioning are for the symfony users. If the new meilisearch-php client in the package does not breaking the symfony code of the users, it's not breaking :)

**Review by bidoubiwa — APPROVED** [review]

**Pull request merged**
