### PR TITLE
Added raw search (fixes #17)

### LINKED ISSUE #17: Add raw search?
Looking at [`MeiliSearchService->search()`](https://github.com/meilisearch/meilisearch-symfony/blob/master/src/Services/MeiliSearchService.php#L207) it requires an `ObjectManager`. 

While i do get the idea behind it, there should be a way to call the raw results without getting the entities from the database, something like this:

```php
    public function searchRaw(
        string $className,
        string $query = '',
        array $requestOptions = []
    ): array {
        $this->assertIsSearchable($className);

        return $this->engine->search($query, $this->searchableAs($className), $requestOptions);
    }
```

Performance-wise its faster getting the data directly from MS than waiting for the "real" entities from MySQL. 

What do you think?

### PR DESCRIPTION
**Pull request by althaus**

### CODE REVIEW

**Review by curquiza — COMMENTED** [review]
Awesome!!! Thanks for your pR!

Could you please rename it "rawSearch" instead of "searchRaw"?

**Comment by althaus** [comment]
@curquiza I've renamed the method accordingly.

**Review by curquiza — APPROVED** [review]
You rock!!!

bors merge

**Comment by curquiza** [comment]
@althaus We would like to highlight your work and thank you for your involvement via the MeiliSearch Twitter account. Do you agree with tagging your Twitter account in MeiliSearch's tweet? 🙂

**Pull request merged**
